[package]
name = "opossync"
version = "0.1.0"
authors = ["Guillaume Charmetant <cguille.dev@gmail.com>"]
description = "Ebook reading position synchronization server."

[dependencies]
actix-web = "0.6"
log = "*"
simplelog = "*"